blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ GitHub Discussions
    url: https://github.com/pmtraders/pmtraders/discussions
    about: If you have a support question or need help getting pmtraders to work, please use GitHub Discussions.
